version: '3'
services:
  ladder:
    image: ghcr.io/everywall/ladder:latest
    container_name: ladder
    #build: .
    #restart: always
    #command: sh -c ./ladder
    environment:
      - PORT=8080
      - RULESET=/app/ruleset.yaml
      #- ALLOWED_DOMAINS=example.com,example.org
      #- ALLOWED_DOMAINS_RULESET=false
      #- EXPOSE_RULESET=true
      #- PREFORK=false
      #- DISABLE_FORM=false
      #- FORM_PATH=/app/form.html
      #- X_FORWARDED_FOR=66.249.66.1
      #- USER_AGENT=Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
      #- USERPASS=foo:bar
      #- LOG_URLS=true
      #- GODEBUG=netdns=go
    ports:
      - "8080:8080"
    volumes:
      - ./ruleset.yaml:/app/ruleset.yaml
      - ./handlers/form.html:/app/form.html